import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Trust from '@/components/Trust/Trust'
import Finance from '@/components/Finance/Finance'
import Info from '@/components/Info/Info'
import Description from '@/components/Description/Description'
import About from '@/components/About/About'
import Xzzz from '@/components/Info/xzzzz'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Description />
      <About />
      <Trust />
      <Info />
      <Finance />
    </>
  )
}
